version: '3.8'

services:
  stock-insight:
    build: .
    container_name: stock-insight-app
    ports:
      - "8080:80"
    volumes:
      # 持久化数据库
      - ./data:/app/backend/data
      # 持久化日志
      - ./logs:/var/log/stock-insight
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stock-insight-network

  # 可选：添加 Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: stock-insight-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - stock-insight-network

volumes:
  redis-data:
    driver: local

networks:
  stock-insight-network:
    driver: bridge